export const GET_ALL_PEOPLE_SUCCESS = 'GET_ALL_PEOPLE_SUCCESS';
export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const GET_HIDDEN_PEOPLE_SUCCESS = 'GET_HIDDEN_PEOPLE_SUCCESS';
export const TOGGLE_PERSON_VISIBILITY_SUCCESS = 'TOGGLE_PERSON_VISIBILITY_SUCCESS';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
