export const GET_ALL_OPINION_SUCCESS = 'GET_ALL_OPINION_SUCCESS';
export const ADD_OPINIONS_SUCCESS = 'ADD_OPINION_SUCCESS';
export const DELETE_OPINION_SUCCESS = 'DELETE_OPINION_SUCCESS';
export const UPDATE_OPINION_SUCCESS = 'UPDATE_OPINION_SUCCESS';
